[build]
  base = "messenger-min"
  command = "npm run build"
  publish = "messenger-min/dist"


[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200